# netlify.toml

[build]
  base    = "frontend"
  command = "yarn && yarn build"
  publish = "frontend/dist"
  functions = "frontend/netlify/functions"

########################################
# SPA 라우팅
########################################
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

########################################
# 캐시 정책
# - index.html : 항상 네트워크 (최신)
# - assets     : 해시가 붙으므로 1년 캐시
########################################
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "max-age=0, must-revalidate"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# (선택) service-worker 파일은 즉시 업데이트
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"
