# netlify.toml

[build]
  # 루트에서 frontend로 들어가 빌드
  command   = "yarn --cwd frontend install --frozen-lockfile && yarn --cwd frontend build"
  publish   = "frontend/dist"
  functions = "frontend/netlify/functions"
  # base 는 쓰지 않습니다 (중복 경로 방지)

########################################
# SPA 라우팅
########################################
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200

########################################
# 캐시 정책
########################################
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "max-age=0, must-revalidate"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"
