# 이 파일은 프로젝트 루트(D:/hellopiggy/netlify.toml)에 위치해야 합니다.

# --- 빌드 설정 ---
[build]
  # 베이스 디렉토리: 모든 빌드 관련 경로는 이 폴더를 기준으로 합니다.
  base = "frontend"

  # 빌드 명령: 'frontend' 폴더 안에서 실행됩니다.
  # 'yarn && yarn build'도