# render.yaml (최종본)
services:
  - type: web
    name: hellopiggy-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    # monorepo 구조이므로, 빌드 컨텍스트를 backend 폴더로 지정
    dockerContext: ./backend
    autoDeploy: true
    plan: free
    # 디스크 설정은 Docker 환경에서 불필요할 수 있으나, 만약을 위해 추가
    disk:
      name: chrome-cache
      mountPath: /root/.cache
      sizeGB: 1