services:
  - type: web
    name: hellopiggys-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    # monorepo 구조이므로, 빌드 컨텍스트를 backend 폴더로 지정
    dockerContext: ./backend
    autoDeploy: true
    plan: free